name: Auto Deploy Bricks to BrickHub.dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Dart and Pub Dependencies
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.2.3' # replace with desired version
          channel: stable

      - name: Install Mason CLI
        run: dart pub global activate mason_cli

      - name: Mason Login
        run: |
          echo quangtuyen1993@gmail.com
          echo Kieungan@2607
          
      - name: Release to BrickHub.dev
        run: mason publish --directory bricks/ddd-template  

